DROP TABLE TB_USUARIO_GE CASCADE CONSTRAINTS;
DROP TABLE TB_ENDERECO_GE CASCADE CONSTRAINTS;
DROP TABLE TB_ORCAMENTO_PAINEL_SOLAR_GE CASCADE CONSTRAINTS;
DROP TABLE TB_HISTORICO_ENERGIA_ELETRICA_GE CASCADE CONSTRAINTS;

CREATE TABLE TB_USUARIO_GE (
   ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   NOME VARCHAR2(100) NOT NULL,
   TELEFONE VARCHAR2(11) NOT NULL,
   EMAIL VARCHAR2(150) UNIQUE NOT NULL,
   SENHA VARCHAR2(100) NOT NULL
);

CREATE TABLE TB_ENDERECO_GE (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_USUARIO NUMBER NOT NULL,
    LOGRADOURO VARCHAR2(200) NOT NULL,
    BAIRRO VARCHAR2(100) NOT NULL,
    CEP VARCHAR2(20) NOT NULL,
    NUMERO_RESIDENCIA NUMBER NOT NULL,
    CIDADE VARCHAR2(100) NOT NULL,
    TIPO_LOCAL VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_TB_ENDERECO_GE FOREIGN KEY (ID_USUARIO)
    REFERENCES TB_USUARIO_GE(ID)
    ON DELETE CASCADE
);

CREATE TABLE TB_ORCAMENTO_PAINEL_SOLAR_GE(
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_ENDERECO INTEGER NOT NULL,
    CUSTO_INVESTIMENTO DECIMAL NOT NULL,
    TAMANHO_SISTEMA DECIMAL NOT NULL,
    NUMERO_MODULOS INTEGER NOT NULL,
    PRODUCAO_ANUAL_ESTIMADA DECIMAL NOT NULL,
    CONSTRAINT FK_ID_ENDERECO_GE_TB_ORCAMENTO_PAINEL_SOLAR_GE FOREIGN KEY (ID_ENDERECO)
    REFERENCES TB_ENDERECO_GE(ID)
    ON DELETE CASCADE
);

CREATE TABLE TB_HISTORICO_ENERGIA_ELETRICA_GE(
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_ENDERECO INTEGER NOT NULL,
    CONSUMO DECIMAL NOT NULL,
    UNIDADE_MEDIDA VARCHAR(10) NOT NULL,
    DATA_REGISTRO DATE NOT NULL,
    CUSTO DECIMAL NOT NULL,
    CONSTRAINT FK_ID_ENDERECO_TB_HISTORICO_ENERGIA_ELETRICA_GE
    FOREIGN KEY (ID_ENDERECO)
    REFERENCES TB_ENDERECO_GE(ID)
    ON DELETE CASCADE
);


