package gs.solinveste.model;

public class SolarPanelCalculator {

    private double monthlyConsumption;  // In kWh
    private double energyCost; // Cost per kWh
    private double panelCost; // Cost of a solar panel
    private double panelPower; // Power generated by a panel (in kwh/month)

    public SolarPanelCalculator() {
    }

    public SolarPanelCalculator(double monthlyConsumption, double energyCost, double panelCost, double panelPower) {
        this.monthlyConsumption = monthlyConsumption;
        this.energyCost = energyCost;
        this.panelCost = panelCost;
        this.panelPower = panelPower;
    }

    public double getMonthlyConsumption() {
        return monthlyConsumption;
    }

    public void setMonthlyConsumption(double monthlyConsumption) {
        this.monthlyConsumption = monthlyConsumption;
    }

    public double getEnergyCost() {
        return energyCost;
    }

    public void setEnergyCost(double energyCost) {
        this.energyCost = energyCost;
    }

    public double getPanelCost() {
        return panelCost;
    }

    public void setPanelCost(double panelCost) {
        this.panelCost = panelCost;
    }

    public double getPanelPower() {
        return panelPower;
    }

    public void setPanelPower(double panelPower) {
        this.panelPower = panelPower;
    }
}
